name: sanitizers

on: [push, pull_request, workflow_dispatch]

jobs:
  asan:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt install -y make gcc
      - run: gcc --version
      - run: make CFLAGS="-g -fno-omit-frame-pointer -fsanitize=address" LDFLAGS="-fsanitize=address"
      # if timeouts (return code 124), consider it a success
      - run: timeout 120 ./dudect_simple_O0 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      - run: timeout 120 ./dudect_simple_O2 || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
